export interface ProcessPhase {
  phase: number;
  title: string;
  duration: string;
  description: string;
}

export interface ServiceConfig {
  slug: string;
  h1: string;
  subhead: string;
  problemSolution: string;
  included: string[];
  whoItsFor: string;
  howItFits: { label: string; href: string }[];
  workingWithYdm: string;
  faqs: { q: string; a: string }[];
  finalCtaText: string;
  selectClients: boolean;
  disclaimer?: string;
  metaTitle: string;
  metaDescription: string;
  processPhases: ProcessPhase[];
  processDisclaimer: boolean;
}

export const SERVICES_CONFIG: Record<string, ServiceConfig> = {
  'web-design': {
    slug: 'web-design',
    h1: 'Website Design That Turns Visitors Into Customers',
    subhead: "Whether it's a first website or an overhaul of one that isn't working, expect custom website design and development — fast to load, mobile-ready, and built around how a small business actually runs. No templates, no guesswork.",
    problemSolution: "Problem / Solution\n\nAn outdated, slow, or non-mobile site makes you invisible to most potential customers. A custom-built site changes that: designed around your business, how people search for you, and what they need to see before they call or buy.",
    included: [
      'Custom design — no template',
      'Mobile-friendly layout',
      'On-page SEO built in from day one',
      'Fast load speeds, tested pre-launch',
      'Contact forms and lead capture integrated',
      'A simple update process, or pairing with a maintenance plan',
    ],
    whoItsFor: 'Starting from scratch. Outdated sites that no longer represent the business. Local service providers who need to be found and trusted online. Startups that need a landing page that converts.',
    howItFits: [
      { label: 'SEO & AI Search Optimization', href: '/services/seo' },
      { label: 'Analytics & Attribution', href: '/services/analytics' },
      { label: 'Website Maintenance', href: '/services/maintenance' },
    ],
    workingWithYdm: "Handled directly by the professional assigned to the project — no handoffs. AI-augmented tools speed up the repetitive work without cutting corners on the parts that matter. Progress is visible through prototypes and staging previews along the way. A live, tested site is delivered on the business's own domain.",
    faqs: [
      { q: 'How long does a website project take?', a: 'Most projects take 2 to 4 weeks from approved scope to launch, depending on the number of pages and any custom functionality involved.' },
      { q: 'Will I need to know how to code to update my own site?', a: "No. Straightforward content updates don't require any technical background. For anything more involved, a maintenance plan is available." },
      { q: 'I already have a site — will a redesign hurt my search rankings?', a: "No. Existing SEO value is preserved during a redesign. URLs, page structure, and search-visible content are carried over deliberately so rankings aren't lost in the process." },
      { q: 'Why custom-built instead of a template?', a: "Templates are built to be generic, which limits flexibility and often hurts performance. A custom build is designed around the specific business, its content, and its goals from day one — with room to grow later without hitting a template's ceiling." },
      { q: "I don't know exactly what I need yet — can you help me figure it out?", a: 'Yes. Full guidance is provided for businesses starting from scratch. The first conversation is about understanding the business and its goals; the site plan gets built from there.' },
      { q: 'Does using AI tools mean corners get cut?', a: "AI speeds up the repetitive parts of the build — boilerplate code, first-pass layouts — the parts that don't need a human's judgment. Design decisions, code quality, and testing are done manually, the same as they'd be without AI in the loop. The speed comes from skipping busywork, not from skipping review." },
      { q: 'How much does a website cost?', a: 'Every project is scoped individually based on pages, features, and timeline, so no single number fits all cases. The free project outline includes a clear, transparent estimate before any commitment is made.' },
    ],
    finalCtaText: 'Ready for a website that works as hard as you do?',
    selectClients: false,
    metaTitle: 'Custom Website Design & Development for Small Businesses | YDM Agency',
    metaDescription: 'Custom-built websites for small businesses — fast, mobile-ready, and designed to turn visitors into customers. No templates. See the process and get a free project outline.',
    processPhases: [
      { phase: 1, title: 'Discovery & Strategy', duration: '1–3 days', description: 'Your business, goals, and requirements are documented. Site structure and content needs are defined.' },
      { phase: 2, title: 'Design & Prototyping', duration: '3–7 days', description: 'Visual design is created and refined. Interactive prototypes let you see and test the layout before build.' },
      { phase: 3, title: 'AI-Assisted Build & Review', duration: '1–3 weeks', description: 'The site is built using modern frameworks. Staging previews are shared for feedback at key milestones.' },
      { phase: 4, title: 'Testing, Launch & Handoff', duration: '2–3 days', description: 'Performance, accessibility, and integration testing is completed. The site goes live and documentation is provided.' },
    ],
    processDisclaimer: false,
  },
  'seo': {
    slug: 'seo',
    h1: 'Get Found by the Customers Already Searching for You',
    subhead: 'Whether starting from scratch, recovering lost rankings, or preparing for AI-powered search, expect a combined approach that gets a business found — on Google and through the AI tools more people are asking instead.',
    problemSolution: "Problem / Solution\n\nEven the best website is invisible if it doesn't show up when someone searches — and today that means showing up in two places at once: traditional results like Google, and AI tools like ChatGPT and Perplexity, which more people ask instead of typing a search query. A site invisible in either place is losing customers who never knew it existed. YDM Agency addresses both with a combined technical, on-page, and AI-search-readiness approach, so visibility isn't left to chance in the channels that matter now.",
    included: [
      'Technical SEO audit & fixes',
      'On-page optimization matched to real customer searches',
      'Local SEO (Google Business Profile), so nearby searches turn into calls and visits',
      'AI search optimization — structuring site content so tools like ChatGPT and Perplexity can find and recommend the business, not just traditional search engines',
      'Plain-English monthly reporting',
      'Initial improvements in 30–60 days, full results over 3–6 months',
    ],
    whoItsFor: 'Not generating search leads. Local service providers who need to be found nearby. Businesses previously burned by an SEO vendor. Forward-thinking owners preparing for AI-powered search.',
    howItFits: [
      { label: 'Website Design & Development', href: '/services/web-design' },
      { label: 'Analytics & Attribution', href: '/services/analytics' },
      { label: 'Reputation & Review Management', href: '/services/reputation' },
    ],
    workingWithYdm: "A roadmap delivered in month one, then consistent monthly execution paired with plain-English reporting — no jargon-heavy PDFs. No lock-in; the plan adjusts monthly based on what's working. Meaningful results build over 3–6 months, and that timeline is set honestly upfront, not oversold.",
    faqs: [
      { q: 'How long until I see results?', a: "Initial improvements typically show up in 30–60 days, with meaningful, significant results building over 3–6 months. Anyone promising overnight rankings isn't being straight about how search works." },
      { q: 'Do you guarantee #1 rankings?', a: "No — no one controls Google's algorithm, so that guarantee isn't an honest one to make. What's guaranteed is transparent, consistent work each month, reported in plain English, with no hidden tactics." },
      { q: 'What is AI search optimization, and do I actually need it?', a: "More people now ask AI tools like ChatGPT and Perplexity questions instead of typing a Google search. AI search optimization structures a site's content so those tools can find, understand, and recommend the business — the same job traditional SEO does for Google. It's a growing second channel, not a replacement for traditional search." },
      { q: 'I was burned by an SEO company before — how is this different?', a: "Plain-English monthly reports explain exactly what's being done and why, with no proprietary jargon or vague check-the-box work. No long-term lock-in contract is required either — the work has to keep earning its place." },
      { q: 'My website is already live — do you start from scratch?', a: "No. An existing site gets a technical and on-page audit first, so the plan builds on what's already working instead of discarding it." },
      { q: 'How much does SEO cost?', a: "Every plan is scoped to the size of the business and how competitive its market is, so there isn't one flat number. The free project outline includes a transparent estimate before any commitment is made." },
    ],
    finalCtaText: 'Ready to get found by the customers searching for you right now?',
    selectClients: false,
    metaTitle: 'SEO & AI Search Optimization for Small Businesses | YDM Agency',
    metaDescription: 'SEO and AI search optimization for small businesses — technical fixes, local SEO, and AI-search readiness that help customers find you. No guesswork. See the process and get a free project outline.',
    processPhases: [
      { phase: 1, title: 'Audit & Discovery', duration: '1–2 weeks', description: 'Technical SEO audit is performed. Current rankings, competitors, and search opportunities are identified.' },
      { phase: 2, title: 'Foundation Fixes & On-Page Optimization', duration: '2–4 weeks', description: 'Technical issues are resolved. On-page elements are optimized for target keywords and AI search readiness.' },
      { phase: 3, title: 'Content & Authority Building', duration: 'ongoing monthly', description: 'Content strategy is executed. Authority signals are built through quality content and local SEO efforts.' },
      { phase: 4, title: 'Monthly Reporting & Iteration', duration: 'ongoing', description: 'Progress is tracked and reported monthly. Strategy is adjusted based on performance data.' },
    ],
    processDisclaimer: false,
  },
  'maintenance': {
    slug: 'maintenance',
    h1: 'Stop Worrying Whether Your Website Still Works',
    subhead: 'From hands-off monthly care to emergency fixes, a site stays secure, fast, and up-to-date — without a business owner having to think about it.',
    problemSolution: "Problem / Solution\n\nEvery minute spent chasing a software update, a security patch, or a broken page is a minute pulled away from running the business — and when something does break, it doesn't just cost time. A slow, insecure, or visibly broken site costs the trust of anyone who lands on it while it's down. Most damage like this happens quietly, discovered only after a customer already bounced. A maintenance plan catches problems before they reach that point, so the site stays dependable without needing to be checked on.",
    included: [
      'Software & security updates — closing the gaps that get sites hacked or taken offline',
      'Regular, tested backups — so a worst-case failure is a quick restore, not a rebuild from scratch',
      'Uptime monitoring',
      'Broken-link and bug fixes',
      'Performance checks',
      'Up to 30 minutes of content updates included each month (more available on request)',
    ],
    whoItsFor: "Owners who want to focus on customers, not code. Sites that haven't been touched in months. Existing YDM Agency clients wanting ongoing care after launch. Hacked or broken sites in need of recovery.",
    howItFits: [
      { label: 'Website Design & Development', href: '/services/web-design' },
      { label: 'SEO & AI Search Optimization', href: '/services/seo' },
      { label: 'Analytics & Attribution', href: '/services/analytics' },
    ],
    workingWithYdm: 'A monthly summary covers what was updated and anything that needs attention. Urgent issues are handled directly, with the client notified — not left to discover a problem on their own. The goal is simple: a site that never has to be wondered about.',
    faqs: [
      { q: 'How often is my site actually checked?', a: 'Monthly maintenance cycles handle routine updates and checks, with deeper quarterly reviews catching anything a monthly pass might miss.' },
      { q: 'What if my site was built by someone else?', a: 'Sites from other developers are accepted after a quick audit, so the current setup is understood before any maintenance work begins.' },
      { q: 'My site is already hacked or down — can you help?', a: 'Yes — hacked or down sites get priority recovery, ahead of routine maintenance work.' },
      { q: 'How much does a maintenance plan cost, and is there a contract?', a: 'Plans are month-to-month with no long-term contract. Pricing is scoped to the site and its level of care, so the free project outline includes a clear, transparent estimate before any commitment is made.' },
      { q: 'What happens if I need more than 30 minutes of updates in a month?', a: 'Extra time is billed with pre-approval — nothing gets charged without it being discussed first.' },
      { q: 'Do I need a maintenance plan if my site is brand new?', a: "It's optional early on, but even new sites benefit from security updates and backups from day one — problems are easier to prevent than to fix after the fact." },
    ],
    finalCtaText: 'Ready to stop worrying about your site?',
    selectClients: false,
    metaTitle: 'Website Maintenance & Support Plans for Small Businesses | YDM Agency',
    metaDescription: 'Monthly website maintenance and support — security updates, backups, uptime monitoring, and fast fixes, so a site never becomes a problem. See plans and get a free project outline.',
    processPhases: [
      { phase: 1, title: 'Onboarding & Site Audit', duration: '1–2 days', description: 'Current site state is assessed. Access is secured and backup systems are verified.' },
      { phase: 2, title: 'Monthly Maintenance Cycle', duration: 'ongoing', description: 'Software and security updates are applied. Uptime is monitored and issues are resolved proactively.' },
      { phase: 3, title: 'Quarterly Deep Reviews', duration: 'quarterly', description: 'Comprehensive performance and security reviews are conducted. Recommendations for improvements are provided.' },
    ],
    processDisclaimer: false,
  },
  'analytics': {
    slug: 'analytics',
    h1: 'Know Exactly Where Your Customers Come From',
    subhead: 'Simple, honest tracking is set up and data is turned into plain-English reports — so guessing what\'s working stops.',
    problemSolution: "Problem / Solution\n\nWithout tracking, marketing spend is a guess dressed up as a strategy — money keeps going toward channels that feel like they're working, while no one can actually say which ones are. That uncertainty compounds: budget stays split across everything because nothing proves which piece to double down on. A tracking system built from scratch, or layered onto whatever's already in place, ends that guessing by showing exactly what drives revenue — not just what drives traffic.",
    included: [
      'Channel clarity — seeing exactly how much each source (Google, social, email, ads) actually contributes, not just how much traffic it sends',
      'Conversion tracking (which keywords/campaigns generate calls and form fills)',
      'Automatic "how did you hear about us" insight, without asking every customer',
      'Page performance and drop-off identification — seeing exactly where visitors leave before converting',
      'Month-over-month trends with clear recommendations, not just numbers',
      'Full setup included, on new or existing analytics accounts',
    ],
    whoItsFor: "Owners who can't answer \"where are my leads actually coming from.\" Teams that need to prove marketing ROI. Anyone ready to double down on what's already working instead of splitting budget evenly across everything.",
    howItFits: [
      { label: 'SEO & AI Search Optimization', href: '/services/seo' },
      { label: 'Paid Advertising', href: '/services/paid-ads' },
      { label: 'CRM & Marketing Automation', href: '/services/automation' },
    ],
    workingWithYdm: "Clean tracking is established first, then monthly plain-English reports follow — with one or two clear action items, not a 40-page data dump nobody reads. All accounts are set up in the client's own name, and a live dashboard is provided for anytime access.",
    faqs: [
      { q: 'I don\'t have any tracking set up right now — where do we start?', a: 'A full install and configuration happens from the ground up — accounts, goals, and dashboards, all set up correctly from day one.' },
      { q: 'I already have Google Analytics — what does this add?', a: 'Custom, revenue-tied goals and dashboards get configured and explained in plain English, so existing data finally means something actionable instead of sitting unused.' },
      { q: 'Can every conversion actually be tracked?', a: "Most digital actions can — form fills, calls initiated from the site, clicks, purchases. Some can't be tracked perfectly by nature, like a walk-in customer who saw the site days earlier or a phone call placed without call tracking enabled. Where that's the case, it's stated plainly rather than papered over with an inflated number." },
      { q: 'How often will I actually see reports?', a: 'A monthly summary is sufficient for most small businesses — enough to act on, without becoming another task to manage.' },
      { q: 'How much does analytics setup cost?', a: "Every analytics setup is scoped to the business, the channels being tracked, and whether existing accounts need cleanup, so there isn't one flat number. The free project outline includes a transparent estimate before any commitment is made." },
      { q: 'Will this tell me if my marketing is actually working, or just show more numbers?', a: 'The reports are built around one question: what should happen next. Every monthly report includes specific action items, not just charts — the number of visitors matters far less than what to do about it.' },
    ],
    finalCtaText: 'Ready to stop guessing and start knowing?',
    selectClients: false,
    metaTitle: 'Marketing Analytics & Attribution for Small Businesses | YDM Agency',
    metaDescription: "Know exactly where customers come from — clean tracking, conversion attribution, and plain-English monthly reports. Stop guessing what's working. Get a free project outline.",
    processPhases: [
      { phase: 1, title: 'Setup & Configuration', duration: '1–2 weeks', description: 'Analytics tools are installed and configured. Conversion tracking is set up for key actions.' },
      { phase: 2, title: 'First Reporting Cycle', duration: '1 month after setup', description: 'Initial data is collected and analyzed. Baseline metrics are established and reported.' },
      { phase: 3, title: 'Monthly Refinement', duration: 'ongoing', description: 'Reports are delivered monthly with clear insights and actionable recommendations.' },
    ],
    processDisclaimer: false,
  },
  'paid-ads': {
    slug: 'paid-ads',
    h1: 'Turn Ad Spend Into Customers, Not Just Clicks',
    subhead: "Whether launching a first campaign or rescuing a budget that's bleeding cash with nothing to show for it, ads are built, managed, and optimized to turn clicks into paying customers.",
    problemSolution: "Problem / Solution\n\nRunning ads without the right structure means paying for clicks that never turn into customers — budget disappears into vague targeting, untested creative, and campaigns nobody's watching closely enough to fix. That's not a strategy, it's a leak, and it usually keeps draining until someone notices the bill. A properly built and actively managed campaign closes that leak: strategy is aligned to a real goal from day one, and every dollar spent is watched, tested, and adjusted — not just spent and hoped for.",
    included: [
      'Campaign strategy aligned to actual business goals, not just impressions',
      'Keyword research and search ad structure (Google), so budget targets people already looking to buy',
      'Audience targeting and creative setup (Meta), so ads reach the people most likely to act on them',
      'Conversion tracking on every click, so spend is tied to results, not guesswork',
      'Ongoing optimization — weekly adjustments, A/B testing',
      'Monthly plain-English report and a live dashboard, always visible',
    ],
    whoItsFor: 'Businesses wanting visibility while SEO builds in the background. Local providers needing a steady, predictable stream of leads. Businesses with at least $500/month available for ad spend.',
    howItFits: [
      { label: 'Website Design & Development', href: '/services/web-design' },
      { label: 'Analytics & Attribution', href: '/services/analytics' },
      { label: 'SEO & AI Search Optimization', href: '/services/seo' },
    ],
    workingWithYdm: "A shared live dashboard means the campaign is never a black box. Daily monitoring and weekly adjustments keep spend efficient, and a monthly report explains plainly what happened and what's changing next. Full visibility, no lock-in contract.",
    faqs: [
      { q: 'How much of my budget actually goes to the ads themselves?', a: "Ad spend is paid directly to the platforms (Google, Meta) using the client's own payment method — it never passes through YDM Agency. Only the separate management fee is invoiced. That means billing can be checked directly against the platform at any time." },
      { q: 'What does managing my campaign actually cost?', a: "Management fees are scoped to the campaign size, number of platforms, and how much ongoing optimization is needed, so there isn't one flat number. The free project outline includes a transparent estimate before any commitment is made." },
      { q: 'Do I need $500/month to get started?', a: "That's the recommended minimum for ads to have enough data to optimize against. Below that, results are harder to read and adjustments take longer to pay off." },
      { q: 'Should I run Google Ads, Meta Ads, or both?', a: "Google captures high-intent searches from people already looking to buy; Meta reaches people based on interest and behavior before they're actively searching. Many businesses use both, aimed at different stages of the same customer journey." },
      { q: 'How fast will I see results?', a: 'Clicks and traffic start immediately once a campaign launches, but meaningful optimization — the kind that actually lowers cost per lead — typically takes 4 to 8 weeks of real data.' },
      { q: 'Do I need a dedicated landing page, or can ads point to my existing site?', a: "A dedicated landing page is strongly recommended, since it's built around one specific offer instead of competing with a homepage's other messages. It can be built alongside the ad campaign if one doesn't exist yet." },
    ],
    finalCtaText: 'Ready to turn your ad budget into measurable growth?',
    selectClients: true,
    disclaimer: 'This service is available for select clients; the exact phases, tools, and timelines may be adapted based on the partnership approach used. Typically delivered in partnership with specialist tools/platforms to ensure quality and reliability. Min. $500/month ad budget recommended.',
    metaTitle: 'Google & Meta Ads Management for Small Businesses | YDM Agency',
    metaDescription: 'Paid advertising management for small businesses — campaigns built, optimized, and reported on with full transparency. Ad spend goes directly to the platforms. Get a free project outline.',
    processPhases: [
      { phase: 1, title: 'Strategy & Goal Setting', duration: '1 week', description: 'Campaign objectives and target audiences are defined. Budget allocation and KPIs are established.' },
      { phase: 2, title: 'Campaign Build & Launch', duration: '1–2 weeks', description: 'Ad creatives and copy are developed. Campaigns are launched with conversion tracking in place.' },
      { phase: 3, title: 'Ongoing Management & Optimization', duration: 'ongoing', description: 'Weekly adjustments and A/B testing are performed. Monthly reports show performance and optimization actions.' },
    ],
    processDisclaimer: true,
  },
  'branding': {
    slug: 'branding',
    h1: 'Branding & Positioning That Makes Customers Choose You',
    subhead: 'Whether starting from scratch, tired of looking inconsistent, or unable to explain why someone should pick this business over the next one — messages are defined, identity is sharpened, and businesses are made unforgettable.',
    problemSolution: "Problem / Solution\n\nA business that looks different on every channel, or can't explain in one sentence why it's worth choosing, loses the comparison before it even starts — a prospect weighing two similar options picks the one that's easier to understand and trust. That gap isn't fixed with a nicer logo alone. It's fixed by defining the message first — who the business serves, what problem it solves, why it's different — and then building the visual identity to carry that message consistently, everywhere it shows up.",
    included: [
      "Positioning statement — who the business serves, the problem it solves, and why it's the right choice",
      'Core messaging (mission, brand promise, elevator pitch) — so the business can be explained clearly in one sentence, not fumbled through',
      'Visual identity (logo refinement or creation, palette, typography, imagery style)',
      'A simple brand style guide, so every future piece — from a social post to a proposal — looks like it came from the same business',
      "Competitive clarity — a clear answer to what makes this business different from the next name on a prospect's list",
    ],
    whoItsFor: "New businesses that need a foundation to build on. Established businesses that have grown inconsistent across channels. Owners who can't yet put into words what makes the business different. Businesses that have simply outgrown their current brand.",
    howItFits: [
      { label: 'Website Design & Development', href: '/services/web-design' },
      { label: 'Content & Copywriting', href: '/services/content' },
      { label: 'Paid Advertising', href: '/services/paid-ads' },
    ],
    workingWithYdm: 'Strategy comes before visuals — deep discovery first, so messaging and identity get built on a real foundation instead of guesswork. All final assets are owned outright by the client once delivered.',
    faqs: [
      { q: 'I already have a logo — do I need to start over?', a: "No. A full brand can be built around an existing logo if it's worth keeping, rather than discarding something that already has recognition." },
      { q: "What's the difference between positioning and a tagline?", a: "Positioning is the internal, strategic foundation — who's served, what problem is solved, why this business specifically. A tagline is the short, customer-facing line that grows out of that foundation. Both are covered, but they're not the same thing." },
      { q: 'Will a rebrand feel jarring to my current customers?', a: "There's usually a short adjustment period while new materials roll out across the website, social channels, and anywhere else the old identity lived — that's normal and expected, not something to pretend away. Once it's live everywhere consistently, most businesses find loyal customers adjust quickly, especially when the new brand actually captures what they already valued about the business." },
      { q: 'How long does a branding project take?', a: 'Most branding projects take 2 to 4 weeks, depending on how much visual identity work is involved alongside the messaging.' },
      { q: 'How much does branding cost?', a: "Every branding project is scoped to the amount of messaging and visual identity work needed, so there isn't one flat number. The free project outline includes a transparent estimate before any commitment is made." },
      { q: "I'm not a 'creative' person — how involved do I need to be?", a: 'Deep discovery upfront does most of the heavy lifting. Direction and feedback are needed at key points, but the strategic and creative work itself is handled directly.' },
    ],
    finalCtaText: 'Ready for a brand that does the selling before you even open your mouth?',
    selectClients: false,
    metaTitle: 'Branding & Positioning for Small Businesses | YDM Agency',
    metaDescription: 'Branding and positioning that makes customers choose you — messaging, visual identity, and a style guide built to make a business unforgettable. See the process and get a free project outline.',
    processPhases: [
      { phase: 1, title: 'Discovery & Research', duration: '3–5 days', description: 'Your business, market, and competitors are researched. Brand positioning opportunities are identified.' },
      { phase: 2, title: 'Messaging & Positioning', duration: '3–5 days', description: 'Core messaging is defined. Positioning statement, mission, and brand promise are crafted.' },
      { phase: 3, title: 'Visual Identity Development', duration: '1–2 weeks', description: 'Logo, color palette, typography, and imagery style are created. Brand guidelines are documented.' },
      { phase: 4, title: 'Application & Handoff', duration: '2–3 days', description: 'Brand assets are finalized and delivered. Implementation guidance is provided.' },
    ],
    processDisclaimer: false,
  },
  'content': {
    slug: 'content',
    h1: 'Words That Turn Visitors Into Customers',
    subhead: 'Great design gets someone to look. Great words get someone to act. Whether a full website is needed written from scratch, a landing page that converts, or ongoing content that brings in search traffic — copy is written that sounds like you and sells like crazy.',
    problemSolution: '',
    included: [
      'Website copy (home, about, services, contact)',
      'Landing page copy built around a single goal',
      'Blog and article content (SEO‑aware, interesting)',
      'Discovery process to capture your voice',
      'Revisions to ensure the final copy feels authentically yours',
    ],
    whoItsFor: 'New businesses needing complete website copy, those whose site doesn’t clearly explain what they do, product/service launches, ongoing blog content for SEO.',
    howItFits: [
      { label: 'Pair with Web Design so words and visuals work together', href: '/services/web-design' },
      { label: 'Pair with Branding & Positioning to define the message before writing', href: '/services/branding' },
      { label: 'Pair with SEO to ensure copy targets the right search terms', href: '/services/seo' },
    ],
    workingWithYdm: 'Discovery first, then benefit‑driven, conversational copy. AI‑driven audience research combines with human editing, so copy is strategically informed and reads like a real person. Full rights transfer upon delivery.',
    faqs: [
      { q: 'Revisions', a: 'Reasonable back‑and‑forth included.' },
      { q: 'Industry knowledge', a: 'Deep research done before drafting; you bring expertise, YDM Agency translates it.' },
      { q: 'Existing copy', a: 'Can be reviewed and improved rather than started from scratch.' },
      { q: 'SEO', a: 'Every piece is optimized while reading naturally.' },
      { q: 'Voice match', a: 'Discovery captures your tone; refinement until it feels right.' },
    ],
    finalCtaText: 'Ready for words that work as hard as you do?',
    selectClients: false,
    metaTitle: 'Content & Copywriting | YDM Agency',
    metaDescription: 'Copy is written that sounds like you and sells like crazy — benefit‑driven, clear, and conversion‑focused.',
    processPhases: [
      { phase: 1, title: 'Discovery & Voice Capture', duration: '2–4 days', description: 'Your voice and tone are captured through discovery. Audience and messaging goals are defined.' },
      { phase: 2, title: 'First Drafts & Iteration', duration: '1–2 weeks', description: 'Copy is drafted and refined through collaboration. Revisions ensure authenticity and impact.' },
      { phase: 3, title: 'SEO Polish & Final Delivery', duration: '2–3 days', description: 'Final copy is optimized for search. All deliverables are provided in editable format.' },
    ],
    processDisclaimer: false,
  },
  'automation': {
    slug: 'automation',
    h1: 'Never Lose Track of a Lead Again',
    subhead: 'Systems are set up that automatically follow up, flag who to call, and make sure every inquiry gets a response — personalized and on time, even overnight.',
    problemSolution: "Problem / Solution\n\nA lead that doesn't hear back fast enough doesn't wait around — it goes to whichever competitor responded first, and that sale is gone before anyone even realizes it slipped away. Manual follow-up can't keep pace with every inquiry, every hour, especially outside business hours when leads still come in but no one's watching. An automated system closes that gap: every inquiry gets acknowledged immediately, routed to the right place, and followed up on schedule — without depending on someone remembering to do it.",
    included: [
      'Instant lead acknowledgment (email/SMS), so no one is left wondering if their message actually went through',
      'Appointment confirmations and reminders',
      'Lead nurture sequences',
      'Lead scoring and routing — surfacing which leads to call first, instead of working through inquiries in whatever order they arrived',
      'Post-project follow-ups (review requests, feedback)',
      'A central dashboard showing every lead and every interaction in one place',
    ],
    whoItsFor: "Businesses currently tracking leads manually. A CRM that's gone dusty and unused. Anyone who's lost a sale to a missed follow-up before. Growing businesses that need a process built to scale, not a spreadsheet held together by habit.",
    howItFits: [
      { label: 'Website Design & Development', href: '/services/web-design' },
      { label: 'Analytics & Attribution', href: '/services/analytics' },
      { label: 'Paid Advertising', href: '/services/paid-ads' },
    ],
    workingWithYdm: "Current lead flow gets audited first, then a workflow is designed around the right tools for that specific business. Every account is set up in the client's own name, with full ownership retained throughout. Documentation and optional training are included, so the system doesn't depend on YDM Agency to keep running day-to-day.",
    faqs: [
      { q: 'Is automated follow-up actually legal and compliant?', a: 'Yes — automated SMS and email outreach is subject to real opt-in and consent rules, and every workflow is built to follow them, not around them. That means proper consent capture and easy opt-out are part of the setup from day one, not an afterthought bolted on later.' },
      { q: "I already have a CRM I'm not using — do we start over?", a: 'Not necessarily. An existing CRM can often be revived and reconfigured rather than replaced outright, if the underlying tool still fits the business.' },
      { q: 'Will automated messages feel spammy to my customers?', a: 'Sequences are designed to feel helpful and personal — timed and worded like a real follow-up, not a mass blast. The goal is a response that feels like it came from a person paying attention, not a script.' },
      { q: 'How long does setup take?', a: 'Most automation builds take 1 to 2 weeks, depending on how many workflows and tools are involved.' },
      { q: 'Can the workflows be adjusted later if my process changes?', a: 'Yes — workflows are built to be flexible and adjusted as the business changes, not locked in permanently at setup.' },
      { q: 'How much does CRM setup and automation cost?', a: "Every CRM and automation setup is scoped to the number of workflows, tools, and integrations needed, so there isn't one flat number. The free project outline includes a transparent estimate before any commitment is made." },
    ],
    finalCtaText: 'Ready to stop losing leads to follow-up gaps?',
    selectClients: true,
    disclaimer: 'This service is available for select clients; the exact phases, tools, and timelines may be adapted based on the partnership approach used. Typically delivered in partnership with specialist tools/platforms to ensure quality and reliability.',
    metaTitle: 'CRM Setup & Marketing Automation for Small Businesses | YDM Agency',
    metaDescription: 'Never lose track of a lead again — automated follow-up, lead routing, and a central dashboard for every inquiry. Compliant by design. Get a free project outline.',
    processPhases: [
      { phase: 1, title: 'Process Audit & Mapping', duration: '2–4 days', description: 'Current lead flow is audited. Automation opportunities are identified and mapped.' },
      { phase: 2, title: 'Tool Selection & Setup', duration: '1–2 weeks', description: 'Appropriate tools are selected. Accounts are set up in your name with full ownership.' },
      { phase: 3, title: 'Workflow Automation & Testing', duration: '1 week', description: 'Automated workflows are built and tested. Documentation and optional training are provided.' },
    ],
    processDisclaimer: true,
  },
  'reputation': {
    slug: 'reputation',
    h1: 'Turn Your Online Reputation Into Your Biggest Asset',
    subhead: 'Most customers check your reviews before they ever call. If your profile is outdated, your reviews are thin, or a bad one is sitting unanswered — business is being lost.',
    problemSolution: "Problem / Solution\n\nA neglected profile doesn't just sit there quietly — it actively costs business every day it's left untouched, since most customers decide whether to call before they ever speak to anyone, based entirely on what they see on the profile first. That damage compounds over time: outdated info erodes trust, thin reviews make a business look unproven next to competitors with dozens, and one unanswered bad review sits as the first thing every future customer reads. A full audit and an ongoing system fix all three at once — optimizing what's there, building a steady flow of new reviews, and making sure nothing negative goes unaddressed.",
    included: [
      'Google Business Profile setup and full optimization, so the business shows up correctly the moment someone searches nearby',
      'A compliant review-generation system (QR codes, follow-up emails, SMS)',
      "Regular profile posts and updates, signaling an active, trustworthy business to both customers and Google's own ranking signals",
      'Real-time review monitoring and alerts',
      'Professional response drafts for every review, positive and negative',
      'Monthly reputation summary',
    ],
    whoItsFor: '"Near me" search-reliant local businesses. Untouched or neglected profiles. Businesses unsure how to respond to a negative review without making it worse. Anyone without a systematic process for generating new reviews.',
    howItFits: [
      { label: 'SEO & AI Search Optimization', href: '/services/seo' },
      { label: 'CRM & Marketing Automation', href: '/services/automation' },
      { label: 'Website Design & Development', href: '/services/web-design' },
    ],
    workingWithYdm: "A full profile audit comes first, then a review-generation system is built to fit how customers actually interact with the business. Negative reviews get a calm, professional response drafted promptly — never left to sit. Profiles remain under the client's own Google account throughout.",
    faqs: [
      { q: 'Can a bad review just be removed?', a: "Only if it violates platform policy — a fake review, harassment, that kind of thing. A legitimate but unflattering review can't simply be taken down. What works instead is a calm, professional public response, which often does more to build trust with future customers than the negative review does to hurt it." },
      { q: 'Is it okay to offer a discount or incentive for leaving a review?', a: "No — incentivizing reviews isn't allowed under platform policy, and every strategy used here stays fully compliant. More reviews come from making it easy (direct links) and asking at the right moment, not from paying for them." },
      { q: 'My profile is basically empty right now — is that actually hurting me?', a: "Yes, more than most owners realize. An incomplete profile ranks and converts significantly worse than a fully optimized one — it's often the single biggest fixable gap for a local business." },
      { q: 'Who actually owns the Google Business Profile once this is set up?', a: "The business does, fully. Profiles remain under the client's own Google account the entire time — there's no dependency on YDM Agency to keep access." },
      { q: 'How fast are negative reviews addressed?', a: 'Negative reviews are addressed within 24 hours, with a response drafted for approval or, if preferred, posted directly.' },
      { q: 'How much does reputation management cost?', a: "Every reputation management plan is scoped to the business, its current profile state, and how active review management needs to be, so there isn't one flat number. The free project outline includes a transparent estimate before any commitment is made." },
    ],
    finalCtaText: 'Ready to turn your online reputation into your biggest asset?',
    selectClients: true,
    disclaimer: 'This service is available for select clients; the exact phases, tools, and timelines may be adapted based on the partnership approach used. Typically delivered in partnership with specialist tools/platforms to ensure quality and reliability.',
    metaTitle: 'Google Business Profile & Review Management | YDM Agency',
    metaDescription: 'Reputation management for small businesses — profile optimization, a compliant review-generation system, and professional responses to every review. Get a free project outline.',
    processPhases: [
      { phase: 1, title: 'Profile Audit & Optimization', duration: '1–2 days', description: 'Google Business Profile is audited and optimized. Missing information is completed.' },
      { phase: 2, title: 'Review Generation System Setup', duration: '1 week', description: 'Compliant review generation system is built. QR codes and automated requests are configured.' },
      { phase: 3, title: 'Ongoing Monitoring & Response', duration: 'monthly', description: 'Reviews are monitored and responses are drafted. Monthly reputation summaries are provided.' },
    ],
    processDisclaimer: true,
  },
};
