export interface ServiceConfig {
  slug: string;
  h1: string;
  subhead: string;
  problemSolution: string;
  included: string[];
  whoItsFor: string;
  howItFits: { label: string; href: string }[];
  workingWithYdm: string;
  faqs: { q: string; a: string }[];
  finalCtaText: string;
  selectClients: boolean;
  metaTitle: string;
  metaDescription: string;
}

export const SERVICES_CONFIG: Record<string, ServiceConfig> = {
  'web-design': {
    slug: 'web-design',
    h1: 'Website Design & Development for Small Businesses',
    subhead: 'Whether you need your first website or a complete overhaul of one that isn’t working, you’ll get a custom site that turns visitors into customers — fast, mobile‑ready, and built around how you do business.',
    problemSolution: 'If Your Current Site Isn’t Delivering\n\nAn outdated, slow, or non‑mobile site makes you invisible to most potential customers. A custom‑built site changes that: it’s designed around your business, how people search for you, and what they need to see before they call or buy.',
    included: [
      'Custom design built around your brand, not a recycled template.',
      'Mobile‑friendly layout for any device.',
      'On‑page SEO built in from day one.',
      'Fast loading speeds, tested and optimized before launch.',
      'Contact forms and lead capture integrated.',
      'Simple update process — or pair with a maintenance plan for hands‑off care.',
    ],
    whoItsFor: 'Businesses starting from scratch, those with outdated sites, local service providers, startups needing a landing page.',
    howItFits: [
      { label: 'Pair with SEO to ensure the new site gets found', href: '/services/seo' },
      { label: 'Pair with Analytics to track where leads come from', href: '/services/analytics' },
      { label: 'Pair with Maintenance to keep everything secure', href: '/services/maintenance' },
    ],
    workingWithYdm: 'Work is handled directly by the professional assigned to your project, using modern, AI‑augmented tools to build faster without cutting corners. You’ll see progress through prototypes and staging previews, and receive a live, tested site on your domain.',
    faqs: [
      { q: 'Timeline', a: '2–4 weeks typical.' },
      { q: 'Updates', a: 'No coding required; simple process or maintenance plan.' },
      { q: 'Existing site redesign', a: 'Yes, existing SEO value is preserved.' },
      { q: 'Custom vs template', a: 'Custom sites offer greater design flexibility and performance.' },
      { q: 'Starting from scratch', a: 'Full guidance provided.' },
    ],
    finalCtaText: 'Ready for a website that works as hard as you do?',
    selectClients: false,
    metaTitle: 'Website Design & Development | YDM Agency',
    metaDescription: 'Custom websites that turn visitors into customers — fast, mobile‑ready, and built around how you do business.',
  },
  'seo': {
    slug: 'seo',
    h1: 'SEO & AI Search Optimization for Small Businesses',
    subhead: 'Whether starting from scratch, recovering lost rankings, or preparing for AI‑powered search, YDM Agency ensures customers find you — wherever they’re searching.',
    problemSolution: 'If You’re Not Showing Up\n\nEven the best website is invisible without search visibility. And now AI tools like ChatGPT and Perplexity are becoming new discovery channels. This is fixed through a combined technical, on‑page, and AI‑search readiness approach.',
    included: [
      'Technical SEO audit & fixes',
      'On‑page optimization matched to real customer searches',
      'Local SEO (Google Business Profile)',
      'AI search optimization (AEO) – structured entity data',
      'Plain‑English monthly reporting',
      'Initial improvements visible within 30–60 days; full results build over 3–6 months',
    ],
    whoItsFor: 'Businesses not generating search leads, local service providers, those who’ve been burned before, forward‑thinking owners.',
    howItFits: [
      { label: 'Pair with Web Design for a strong foundation', href: '/services/web-design' },
      { label: 'Pair with Analytics to track keyword conversions', href: '/services/analytics' },
      { label: 'Pair with Reputation Management to strengthen local signals', href: '/services/reputation' },
    ],
    workingWithYdm: 'SEO is ongoing. A clear roadmap is delivered in month one, then consistent monthly execution and plain‑English reporting. No long‑term lock‑in contracts; services can be adjusted monthly. Meaningful results typically build over 3–6 months, but initial progress is visible sooner.',
    faqs: [
      { q: 'Timeline', a: '30–60 days for initial movement; 3–6 months for significant results.' },
      { q: 'AI search readiness', a: 'More people use AI tools; AEO structures your info for them.' },
      { q: 'Existing site', a: 'Audit first; optimization on top if foundation is solid.' },
      { q: 'Guarantees', a: 'No ethical provider can guarantee #1 rankings; transparent, consistent work is guaranteed.' },
      { q: 'Burned before', a: 'Plain‑English reports every month, no hidden tactics.' },
    ],
    finalCtaText: 'Ready to get found by the customers searching for you right now?',
    selectClients: false,
    metaTitle: 'SEO & AI Search Optimization | YDM Agency',
    metaDescription: 'Customers find you wherever they’re searching — traditional search engines and AI‑powered tools.',
  },
  'maintenance': {
    slug: 'maintenance',
    h1: 'Website Maintenance & Support Plans',
    subhead: 'From hands‑off monthly care to emergency fixes — YDM Agency keeps your site secure, fast, and up‑to‑date.',
    problemSolution: 'Why Maintenance Matters\n\nEvery minute spent on updates, security, or broken pages is time away from your business. And if something breaks, the cost is lost trust. Maintenance plans catch problems before they hurt.',
    included: [
      'Software & security updates',
      'Regular tested backups',
      'Uptime monitoring',
      'Broken link and bug fixes',
      'Performance checks',
      'Up to 30 minutes of content updates (additional time available)',
    ],
    whoItsFor: 'Business owners who want to focus on customers, sites that haven’t been updated in months, clients of YDM Agency who want ongoing care, or those dealing with a hacked/broken site.',
    howItFits: [
      { label: 'Pair with Web Design if a rebuild is needed first', href: '/services/web-design' },
      { label: 'Pair with SEO to keep rankings strong as the site evolves', href: '/services/seo' },
      { label: 'Pair with Analytics to track performance impact', href: '/services/analytics' },
    ],
    workingWithYdm: 'A monthly summary of updates and any items needing attention. If something urgent occurs, it’s handled and you’re notified. Never wonder whether your site is okay.',
    faqs: [
      { q: 'Frequency', a: 'Monthly checks; deeper quarterly reviews.' },
      { q: 'Existing site from another developer', a: 'Yes, after a quick audit.' },
      { q: 'Hacked/down site', a: 'Reach out immediately; priority recovery.' },
    ],
    finalCtaText: 'Ready to stop worrying about your site?',
    selectClients: false,
    metaTitle: 'Website Maintenance & Support | YDM Agency',
    metaDescription: 'Sites are kept secure, fast, and up‑to‑date so you never have to think about it.',
  },
  'analytics': {
    slug: 'analytics',
    h1: 'Know Exactly Where Your Customers Come From',
    subhead: 'Simple, honest tracking is set up and data is turned into plain‑English reports — so guessing what’s working stops.',
    problemSolution: 'If You Can’t Trace a Lead\n\nWithout tracking, marketing spend is gambling. This is resolved — whether starting from scratch or making sense of existing analytics, a system is built that shows exactly what drives revenue.',
    included: [
      'Channel clarity (Google, social, email, ads)',
      'Conversion tracking (which keywords/campaigns generate calls or form fills)',
      'Automatic "How did you hear about us?" insight',
      'Page performance & drop‑off identification',
      'Month‑over‑month trends with clear recommendations',
      'Full setup included',
    ],
    whoItsFor: 'Business owners running marketing who can’t answer "Where are my leads coming from?", teams that need to prove ROI, anyone ready to double down on what works.',
    howItFits: [
      { label: 'Pair with SEO to track keyword conversions', href: '/services/seo' },
      { label: 'Pair with Paid Advertising to measure ad return', href: '/services/paid-ads' },
      { label: 'Pair with CRM & Automation to connect marketing data to sales', href: '/services/automation' },
    ],
    workingWithYdm: 'Clean tracking is established, then monthly reports are delivered in plain English with one or two action items. No 40‑page data dumps.',
    faqs: [
      { q: 'No existing tracking', a: 'All tools installed and configured.' },
      { q: 'Already have Google Analytics', a: 'Custom goals and dashboards that tie to revenue are configured and explained.' },
      { q: 'Frequency', a: 'Monthly summary is enough for most small businesses.' },
    ],
    finalCtaText: 'Ready to stop guessing and start knowing?',
    selectClients: false,
    metaTitle: 'Analytics & Reporting | YDM Agency',
    metaDescription: 'Simple, honest tracking turns data into plain‑English reports — so guessing what’s working stops.',
  },
  'paid-ads': {
    slug: 'paid-ads',
    h1: 'Google & Meta Ads Management for Small Businesses',
    subhead: 'Whether starting your first campaign or rescuing a budget that’s bleeding cash, ads are built, managed, and optimized to turn clicks into customers.',
    problemSolution: 'Note: This service is available for clients with a minimum $500/month ad budget. Campaigns are set up, monitored, and adjusted; ad spend is paid directly to the platforms by the client. Management is transparent, with no long‑term lock‑in.',
    included: [
      'Campaign strategy aligned with business goals',
      'Keyword research and search ad structure (Google Ads)',
      'Audience targeting and creative setup (Meta Ads)',
      'Conversion tracking for every click',
      'Ongoing optimization (weekly adjustments, A/B testing)',
      'Monthly plain‑English reporting with live dashboard access',
    ],
    whoItsFor: 'Businesses wanting immediate visibility while SEO builds, local service providers needing a steady lead flow, those spending at least $500/month on ad budget.',
    howItFits: [
      { label: 'Pair with Web Design for dedicated landing pages', href: '/services/web-design' },
      { label: 'Pair with Analytics to prove campaign ROI', href: '/services/analytics' },
      { label: 'Pair with SEO for long‑term organic growth', href: '/services/seo' },
    ],
    workingWithYdm: 'A shared live dashboard, daily monitoring, weekly adjustments, and a monthly report explaining not just what happened but what’s being done about it. Full visibility; no lock‑in.',
    faqs: [
      { q: 'Budget', a: '$500/month ad spend recommended as minimum.' },
      { q: 'Google vs Meta', a: 'Google captures high‑intent search; Meta reaches by interest and behavior. Many use both.' },
      { q: 'Timeline', a: 'Clicks start immediately; meaningful optimization takes 4–8 weeks.' },
      { q: 'Landing pages', a: 'Strongly recommended; can be built alongside ad management.' },
    ],
    finalCtaText: 'Ready to turn your ad budget into measurable growth?',
    selectClients: true,
    metaTitle: 'Paid Advertising | YDM Agency',
    metaDescription: 'Ads are built, managed, and optimized to turn clicks into customers — not just spend.',
  },
  'branding': {
    slug: 'branding',
    h1: 'Branding & Positioning That Makes Customers Choose You',
    subhead: 'Whether starting from scratch, tired of looking inconsistent, or unable to explain why someone should pick you — messages are defined, identity is sharpened, and businesses are made unforgettable.',
    problemSolution: '',
    included: [
      'Positioning statement that sticks (who you serve, problem you solve, why you’re the right choice)',
      'Core messaging: mission, brand promise, elevator pitch',
      'Visual identity: logo refinement/creation, color palette, typography, imagery style',
      'Simple brand style guide for consistency across all media',
      'Competitive clarity',
    ],
    whoItsFor: 'New businesses needing a foundation, established businesses with inconsistent marketing, those who can’t articulate their advantage, companies that have outgrown their current brand.',
    howItFits: [
      { label: 'Pair with Web Design to translate brand into a cohesive site', href: '/services/web-design' },
      { label: 'Pair with Content & Copywriting to give the brand a voice', href: '/services/content' },
      { label: 'Pair with Paid Advertising for consistent campaign messaging', href: '/services/paid-ads' },
    ],
    workingWithYdm: 'Strategy before visuals. Deep discovery, then messaging and identity built on a solid foundation. You’ll own all final assets.',
    faqs: [
      { q: 'Already have a logo?', a: 'Full brand can be built around it.' },
      { q: 'Positioning vs tagline', a: 'Positioning is internal and strategic; tagline is customer‑facing. Both are covered.' },
      { q: 'Rebranding and existing customers', a: 'A strong rebrand sharpens identity rather than replacing it; loyal customers often feel it finally captures what they love.' },
      { q: 'Timeline', a: 'Typically 2–4 weeks.' },
    ],
    finalCtaText: 'Ready for a brand that does the selling before you even open your mouth?',
    selectClients: false,
    metaTitle: 'Branding & Positioning | YDM Agency',
    metaDescription: 'Messages are defined, identity is sharpened, and businesses are made unforgettable.',
  },
  'content': {
    slug: 'content',
    h1: 'Words That Turn Visitors Into Customers',
    subhead: 'Great design gets someone to look. Great words get someone to act. Whether a full website is needed written from scratch, a landing page that converts, or ongoing content that brings in search traffic — copy is written that sounds like you and sells like crazy.',
    problemSolution: '',
    included: [
      'Website copy (home, about, services, contact)',
      'Landing page copy built around a single goal',
      'Blog and article content (SEO‑aware, interesting)',
      'Discovery process to capture your voice',
      'Revisions to ensure the final copy feels authentically yours',
    ],
    whoItsFor: 'New businesses needing complete website copy, those whose site doesn’t clearly explain what they do, product/service launches, ongoing blog content for SEO.',
    howItFits: [
      { label: 'Pair with Web Design so words and visuals work together', href: '/services/web-design' },
      { label: 'Pair with Branding & Positioning to define the message before writing', href: '/services/branding' },
      { label: 'Pair with SEO to ensure copy targets the right search terms', href: '/services/seo' },
    ],
    workingWithYdm: 'Discovery first, then benefit‑driven, conversational copy. AI‑driven audience research combines with human editing, so copy is strategically informed and reads like a real person. Full rights transfer upon delivery.',
    faqs: [
      { q: 'Revisions', a: 'Reasonable back‑and‑forth included.' },
      { q: 'Industry knowledge', a: 'Deep research done before drafting; you bring expertise, YDM Agency translates it.' },
      { q: 'Existing copy', a: 'Can be reviewed and improved rather than started from scratch.' },
      { q: 'SEO', a: 'Every piece is optimized while reading naturally.' },
      { q: 'Voice match', a: 'Discovery captures your tone; refinement until it feels right.' },
    ],
    finalCtaText: 'Ready for words that work as hard as you do?',
    selectClients: false,
    metaTitle: 'Content & Copywriting | YDM Agency',
    metaDescription: 'Copy is written that sounds like you and sells like crazy — benefit‑driven, clear, and conversion‑focused.',
  },
  'automation': {
    slug: 'automation',
    h1: 'CRM Setup & Marketing Automation for Small Businesses',
    subhead: 'Never lose track of a lead again. Systems are set up that automatically follow up, remind who to call, and make sure every inquiry gets a response — personalized and on time.',
    problemSolution: 'Note: This service is available for select clients. YDM Agency typically delivers it in partnership with specialist tools and platforms to ensure quality and reliability.',
    included: [
      'Instant lead acknowledgment (email/SMS)',
      'Appointment confirmations and reminders',
      'Lead nurture sequences',
      'Lead scoring and routing',
      'Post‑project follow‑ups (review requests, feedback)',
      'Central dashboard showing every lead and interaction',
    ],
    whoItsFor: 'Business owners tracking leads manually, teams with a dusty CRM, anyone who’s lost a sale due to a missed follow‑up, growing businesses needing scalable processes.',
    howItFits: [
      { label: 'Pair with Web Design to capture leads directly into workflows', href: '/services/web-design' },
      { label: 'Pair with Analytics to track automation performance', href: '/services/analytics' },
      { label: 'Pair with Paid Advertising to ensure ad clicks land in nurture sequences', href: '/services/paid-ads' },
    ],
    workingWithYdm: 'Starting with an audit of current lead flow, then designing a workflow using appropriate tools. All accounts are set up in your name; you retain full ownership. Documentation and optional training provided.',
    faqs: [
      { q: 'Existing CRM?', a: 'Can be revived or replaced.' },
      { q: 'Robotic feel?', a: 'Sequences are designed to be helpful and personal, not spammy.' },
      { q: 'Timeline', a: 'Typically 1–2 weeks.' },
      { q: 'Changes', a: 'Workflows are flexible; adjustments can be made later.' },
    ],
    finalCtaText: 'Ready to stop losing leads to follow‑up gaps?',
    selectClients: true,
    metaTitle: 'CRM & Marketing Automation | YDM Agency',
    metaDescription: 'Systems are set up that automatically follow up, remind who to call, and make sure every inquiry gets a response.',
  },
  'reputation': {
    slug: 'reputation',
    h1: 'Google Business Profile & Review Management',
    subhead: 'Most customers check your reviews before they ever call. If your profile is outdated, your reviews are thin, or a bad one is sitting unanswered — business is being lost. This is fixed.',
    problemSolution: 'Note: This service is available for select clients. YDM Agency typically delivers it in partnership with specialist tools and platforms to ensure quality and reliability.',
    included: [
      'Google Business Profile setup and full optimization',
      'Compliant review generation system (QR codes, follow‑up emails, SMS)',
      'Regular profile posts and updates',
      'Real‑time review monitoring with alerts',
      'Professional response drafts for every review (positive and negative)',
      'Monthly reputation summary',
    ],
    whoItsFor: 'Local businesses relying on "near me" searches, those with an untouched profile, businesses that have received a negative review and aren’t sure how to respond, anyone who knows they need more reviews but lacks a system.',
    howItFits: [
      { label: 'Pair with SEO — reviews are a top local ranking factor', href: '/services/seo' },
      { label: 'Pair with CRM & Automation — automate review requests', href: '/services/automation' },
      { label: 'Pair with Web Design — embed reviews on your site', href: '/services/web-design' },
    ],
    workingWithYdm: 'Starting with a full profile audit, then building a review generation system that fits your customer flow. For negative reviews, a calm, professional response is drafted promptly. All profiles remain under your ownership.',
    faqs: [
      { q: 'Removing bad reviews', a: 'Only if they violate platform policies; otherwise, a strong response mitigates damage.' },
      { q: 'Incentivizing reviews', a: 'Not allowed; all strategies are fully compliant.' },
      { q: 'Getting more reviews without pushing', a: 'By making it easy — direct links, well‑timed requests.' },
      { q: 'Incomplete profile impact', a: 'Significant; complete profiles rank higher and convert better.' },
    ],
    finalCtaText: 'Ready to turn your online reputation into your biggest asset?',
    selectClients: true,
    metaTitle: 'Reputation & Review Management | YDM Agency',
    metaDescription: 'Profiles are optimized, a system for collecting genuine reviews is built, and responses are handled.',
  },
};
